folder_map = {
    ".pdf": "PDFs",
    ".jpg": "Images",
    ".jpeg": "Images",
    ".png": "Images",
    ".exe": "Installers",
    ".zip": "Archives",
    ".docx": "Documents",
    ".txt": "Documents",
    ".pptx": "Presentations",
    ".ppt": "Presentations",
    ".csv": "Spreadsheets",
    ".xlsx": "Spreadsheets",
    ".html": "Web",
    ".msi": "Installers",
    ".mp3": "Music",
    ".gdb": "Databases",
    ".tmp": "Temp",
    ".bin": "Binary",
    ".ppkx": "Certificates",
    ".mpk": "Geospatial",
    ".geojson": "Geospatial",
    ".pitemx": "Geospatial",
    ".doc": "Documents",
    ".a": "Audio",
    ".ics": "Calendars",
    ".ini": "Config",
    ".ipynb": "Jupyter Notebooks",
    ".ica": "Citrix",
    ".winmd": "Windows Metadata",

}